name: CRDA

on:
  push:
  pull_request_target:
    # These types are all required for CRDA to scan pull requests correctly and securely.
    types: [ opened, synchronize, reopened, labeled, edited ]

jobs:
  crda:
    name: CRDA
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install CRDA
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        source: github
        crda: latest

    - name: CRDA Scan
      id: crda_scan
      uses: redhat-actions/crda@main
      with:
        crda_key: ${{ secrets.CRDA_KEY }}
